### ISSUE TITLE
How I can compile it?

### ISSUE THREAD

**Issue by ners11** [Lefinnois/hackrf_ook#1]
Help me please. I cant use this prog. How I can compile it in Ubuntu?

**Comment by Lefinnois** [comment]
You need to install "libhackrf-dev", "libglib2.0-dev", "build-essential" and "pkg-config" packages. Then go to the directory and type "make". You will get "hackrf_ook" binary ti play with.

**Comment by ners11** [comment]
Hello. I`m sorry, but I have an error when I try "make". Can U help me please?

ners@X230:~/hackrf_ook-master$ make
gcc `pkg-config --libs libhackrf glib-2.0` -lm  hackrf_ook.o   -o hackrf_ook
hackrf_ook.o: In function `tx_callback':
hackrf_ook.c:(.text+0x9b): undefined reference to `g_main_loop_quit'
hackrf_ook.o: In function `sigint_callback_handler':
hackrf_ook.c:(.text+0xea): undefined reference to `g_main_loop_quit'
hackrf_ook.o: In function `main':
hackrf_ook.c:(.text.startup+0x426): undefined reference to `sincos'
hackrf_ook.c:(.text.startup+0x572): undefined reference to `sincos'
hackrf_ook.c:(.text.startup+0x6b1): undefined reference to `g_main_loop_new'
hackrf_ook.c:(.text.startup+0x734): undefined reference to `hackrf_init'
hackrf_ook.c:(.text.startup+0x748): undefined reference to `hackrf_open'
hackrf_ook.c:(.text.startup+0x768): undefined reference to `hackrf_set_sample_rate_manual'
hackrf_ook.c:(.text.startup+0x77c): undefined reference to `hackrf_compute_baseband_filter_bw_round_down_lt'
hackrf_ook.c:(.text.startup+0x78a): undefined reference to `hackrf_set_baseband_filter_bandwidth'
hackrf_ook.c:(.text.startup+0x7a5): undefined reference to `hackrf_set_txvga_gain'
hackrf_ook.c:(.text.startup+0x7c2): undefined reference to `hackrf_set_freq'
hackrf_ook.c:(.text.startup+0x7dd): undefined reference to `hackrf_set_amp_enable'
hackrf_ook.c:(.text.startup+0x82f): undefined reference to `hackrf_start_tx'
hackrf_ook.c:(.text.startup+0x845): undefined reference to `g_main_loop_run'
hackrf_ook.c:(.text.startup+0x85b): undefined reference to `g_main_loop_unref'
hackrf_ook.c:(.text.startup+0x86c): undefined reference to `hackrf_stop_tx'
hackrf_ook.c:(.text.startup+0x882): undefined reference to `hackrf_close'
hackrf_ook.c:(.text.startup+0x893): undefined reference to `hackrf_exit'
hackrf_ook.c:(.text.startup+0x984): undefined reference to `sincos'
hackrf_ook.c:(.text.startup+0xa5a): undefined reference to `hackrf_error_name'
hackrf_ook.c:(.text.startup+0xa89): undefined reference to `hackrf_error_name'
hackrf_ook.c:(.text.startup+0xac7): undefined reference to `hackrf_error_name'
hackrf_ook.c:(.text.startup+0xadb): undefined reference to `hackrf_error_name'
hackrf_ook.c:(.text.startup+0xaf2): undefined reference to `hackrf_error_name'
hackrf_ook.o:hackrf_ook.c:(.text.startup+0xb09): more undefined references to `hackrf_error_name' follow
collect2: error: ld returned 1 exit status
<встроенное>: ошибка выполнения рецепта для цели «hackrf_ook»
make: *** [hackrf_ook] Ошибка 1

**Comment by Lefinnois** [comment]
What's the result you have when running 'pkg-config --libs libhackrf glib-2.0' ?
You must get something like "-lhackrf -lglib-2.0".
Is pkg-config installed ?
